Repository lblod/frontend-organization-portal, pull requests merged in 2023-11, with the labels that each got.

#535 Include ROs to religion filter
  app/components/classification-multiple-select.js
  app/controllers/administrative-units/index.js
  app/models/administrative-unit-classification-code.js
  app/templates/administrative-units/index.hbs
Labels: bug

#536 Make all organizations clickable in persons module
  app/routes/people/index.js
  app/templates/people/index.hbs
  app/templates/people/person/personal-information/index.hbs
  app/templates/people/person/positions/index.hbs
Labels: enhancement

#537 post processing to open editor links in a new tab
  app/components/rich-text-editor.js
Labels: enhancement

#539 Hide purpose and planned end date when not filled in
  app/templates/administrative-units/administrative-unit/core-data/edit.hbs
  app/templates/administrative-units/administrative-unit/core-data/index.hbs
  app/templates/administrative-units/new.hbs
Labels: enhancement

#542 Fix: make names of AGB, APB, and IGS clickable on positions page
  app/templates/people/person/positions/agent/index.hbs
Labels: enhancement

#543 Tests fix and cleaning
  tests/integration/helpers/is-last-test.js
  tests/integration/helpers/kbo-format-test.js
  tests/integration/helpers/rrn-format-test.js
  tests/unit/controllers/administrative-units/administrative-unit/related-organizations/edit-test.js
  tests/unit/controllers/administrative-units/administrative-unit/related-organizations/index-test.js
  tests/unit/controllers/application-test.js
  tests/unit/controllers/organizations/organization/core-data-test.js
  tests/unit/controllers/organizations/organization/related-organizations-test.js
  tests/unit/models/decision-activity-test.js
  tests/unit/routes/administrative-units/administrative-unit/related-organizations-test.js
  tests/unit/routes/administrative-units/administrative-unit/related-organizations/edit-test.js
  tests/unit/routes/organizations/organization/core-data-test.js
  tests/unit/routes/organizations/organization/related-organizations-test.js
  tests/unit/routes/redirect-test.js
  tests/unit/services/deep-link-test.js
  tests/unit/services/uri-info-test.js
Labels: internal

#470 feature: use woodpecker ci instead of drone
  .drone.yml
  .woodpecker/.latest.yml
  .woodpecker/.release.yml
  .woodpecker/.test-build.yml
  .woodpecker/.test-pr.yml
Labels: internal

#544 Use woodpecker ci instead of drone - follow up
  .drone.yml
  .woodpecker/.latest.yml
  .woodpecker/.release.yml
  .woodpecker/.test-build.yml
  .woodpecker/.test-pr.yml
  package-lock.json
  package.json
Labels: internal

#541 Refactor: Introduce generic Agent resource
  app/models/agent-in-position.js
  app/models/agent.js
  app/models/functionary.js
  app/models/organization.js
  app/models/person.js
  app/models/post.js
  app/router.js
  app/routes/administrative-units/administrative-unit/executives.js
  app/routes/people/index.js
  app/routes/people/person/positions/agent.js
  app/routes/people/person/positions/functionary.js
  app/routes/people/person/positions/functionary/index.js
  app/routes/people/person/positions/index.js
  app/services/contact-details.js
  app/templates/administrative-units/administrative-unit/executives.hbs
  app/templates/people/person/personal-information/index.hbs
  app/templates/people/person/positions/agent.hbs
  app/templates/people/person/positions/functionary.hbs
  app/templates/people/person/positions/functionary/index.hbs
  app/templates/people/person/positions/index.hbs
Labels: enhancement
