Repository lblod/frontend-organization-portal, pull requests merged in 2023-07, with the labels that each got.

#474 Fix sorting in related organizations tab
  app/components/related-organizations/edit-agb.hbs
  app/components/related-organizations/edit-apb.hbs
  app/components/related-organizations/edit-central-worship-service.hbs
  app/components/related-organizations/edit-municipality.hbs
  app/components/related-organizations/edit-province.hbs
  app/components/related-organizations/view-central-worship-service.hbs
  app/components/related-organizations/view-municipality.hbs
  app/components/related-organizations/view-province.hbs
  app/controllers/administrative-units/administrative-unit/related-organizations/edit.js
  app/routes/administrative-units/administrative-unit/related-organizations/edit.js
  app/templates/administrative-units/administrative-unit/related-organizations/edit.hbs
  app/templates/administrative-units/administrative-unit/related-organizations/index.hbs
  app/templates/administrative-units/administrative-unit/related-organizations/loading.hbs
Labels: bug

#478 Hide organen in menu
  app/controllers/administrative-units/administrative-unit.js
  app/templates/administrative-units/administrative-unit.hbs
Labels: enhancement

#475 Feat/igs add new
  app/components/classification-select.js
  app/components/site-type-select.js
  app/controllers/administrative-units/administrative-unit.js
  app/controllers/administrative-units/new.js
  app/models/administrative-unit-classification-code.js
  app/models/administrative-unit.js
  app/routes/administrative-units/index.js
  app/templates/administrative-units/administrative-unit.hbs
  app/templates/administrative-units/new.hbs
  app/validations/administrative-unit.js
Labels: enhancement

#481 Allow agb and apb in personen filters
  app/components/position-select.js
  app/controllers/people/index.js
  app/models/administrative-unit-classification-code.js
  app/routes/people/index.js
  app/templates/people/index.hbs
  app/templates/people/person/personal-information/index.hbs
  app/templates/people/person/positions/agent/index.hbs
  app/templates/people/person/positions/index.hbs
Labels: enhancement

#477 Change events - IGS
  app/components/change-event-type-select.js
  app/controllers/administrative-units/administrative-unit/change-events/details/edit.js
  app/controllers/administrative-units/administrative-unit/change-events/new.js
  app/models/change-event-type.js
  app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
  app/templates/administrative-units/administrative-unit/change-events/new.hbs
Labels: enhancement

#483 Update text from the landing and home pages
  app/templates/index.hbs
  app/templates/login.hbs
Labels: enhancement

#485 Fix contact point of agents not resolving
  app/services/contact-details.js
Labels: bug

#484 Enable IGS positions in Personen module
  app/components/position-select.js
  app/controllers/people/index.js
  app/models/administrative-unit-classification-code.js
  app/routes/people/index.js
  app/templates/people/index.hbs
  app/templates/people/person/personal-information/index.hbs
  app/templates/people/person/positions/agent/index.hbs
  app/templates/people/person/positions/index.hbs
Labels: enhancement

#486 Fix validations too strict on municipalities
  app/validations/administrative-unit.js
Labels: bug

#488 Text improvements regarding roles
  app/components/app-header.hbs
  app/helpers/convert-role-names.js
  app/templates/select-role.hbs
Labels: enhancement

#487 Set regio as read-only for municipalities
  app/templates/administrative-units/administrative-unit/core-data/edit.hbs
  app/templates/administrative-units/new.hbs
Labels: bug

#489 Links in contact were not working because of this reset controller
  app/routes/contact.js
Labels: bug

#490 Show OVO as readonly even for worship services
  app/templates/administrative-units/administrative-unit/core-data/edit.hbs
Labels: enhancement

#492 Paginate related organizations page
  app/components/related-organizations/view-central-worship-service.hbs
  app/components/related-organizations/view-municipality.hbs
  app/components/related-organizations/view-province.hbs
  app/controllers/administrative-units/administrative-unit/related-organizations/index.js
  app/routes/administrative-units/administrative-unit/related-organizations/index.js
  app/templates/administrative-units/administrative-unit/related-organizations/index.hbs
Labels: enhancement

#491 Bump ember-acmidm-login to v2
  app/components/app-header.hbs
  app/components/app-header.js
  app/components/login-button.hbs
  app/components/page-loader.hbs
  app/controllers/auth/callback.js
  app/router.js
  app/routes/application.js
  app/routes/auth/callback.js
  app/routes/auth/login.js
  app/routes/auth/logout.js
  app/routes/auth/switch.js
  app/routes/callback.js
  app/routes/select-role.js
  app/routes/switch-login.js
  app/services/session.js
  app/templates/login.hbs
  config/environment.js
  package-lock.json
  package.json
Labels: internal

#493 Added a not active toggle to related organizations
  app/components/related-organizations/view-central-worship-service.hbs
  app/components/related-organizations/view-municipality.hbs
  app/components/related-organizations/view-province.hbs
  app/controllers/administrative-units/administrative-unit/related-organizations/index.js
  app/routes/administrative-units/administrative-unit/related-organizations/index.js
  app/templates/administrative-units/administrative-unit/related-organizations/index.hbs
Labels: enhancement
