Repository lblod/frontend-organization-portal, pull requests merged in 2024-01, with the labels that each got.

#556 Add validation so the sharepoint is always a number
  app/controllers/administrative-units/administrative-unit/core-data/edit.js
  app/controllers/administrative-units/new.js
  app/routes/administrative-units/administrative-unit/core-data/edit.js
  app/routes/administrative-units/new.js
  app/templates/administrative-units/administrative-unit/core-data/edit.hbs
  app/templates/administrative-units/new.hbs
  app/validations/administrative-unit.js
Labels: enhancement

#553 Feature: onboarding public ocmw associations
  app/components/administrative-unit-multiple-select.hbs
  app/components/administrative-unit-select.hbs
  app/components/change-event-type-select.js
  app/components/classification-multiple-select.js
  app/components/classification-select.js
  app/components/position-select.js
  app/components/related-organizations/edit-ocmw-association.hbs
  app/components/related-organizations/view-agb.hbs
  app/components/related-organizations/view-apb.hbs
  app/components/related-organizations/view-ocmw-association.hbs
  app/components/site-type-select.js
  app/controllers/administrative-units/administrative-unit.js
  app/controllers/administrative-units/administrative-unit/core-data/edit.js
  app/controllers/administrative-units/administrative-unit/core-data/index.js
  app/controllers/administrative-units/administrative-unit/related-organizations/edit.js
  app/controllers/administrative-units/administrative-unit/related-organizations/index.js
  app/controllers/administrative-units/new.js
  app/controllers/people/index.js
  app/models/administrative-unit-classification-code.js
  app/models/change-event-type.js
  app/models/organization.js
  app/routes/administrative-units/administrative-unit/core-data/edit.js
  app/routes/administrative-units/administrative-unit/core-data/index.js
  app/routes/administrative-units/administrative-unit/related-organizations/index.js
  app/templates/administrative-units/administrative-unit.hbs
  app/templates/administrative-units/administrative-unit/core-data/edit.hbs
  app/templates/administrative-units/administrative-unit/core-data/index.hbs
  app/templates/administrative-units/administrative-unit/related-organizations/edit.hbs
  app/templates/administrative-units/administrative-unit/related-organizations/index.hbs
  app/templates/administrative-units/new.hbs
  app/utils/classification-identifiers.js
  app/validations/administrative-unit.js
  tests/unit/models/administrative-unit-classification-code-test.js
Labels: enhancement

#557 Add feature flag service and helper
  README.md
  app/helpers/is-feature-enabled.js
  app/services/features.js
  config/environment.js
  tests/unit/services/features-test.js
Labels: internal

#558 Feature: onboarding PEVA organisations
  app/components/change-event-type-select.js
  app/components/classification-multiple-select.js
  app/components/classification-select.js
  app/components/related-organizations/edit-peva-municipality.hbs
  app/components/related-organizations/edit-peva-province.hbs
  app/components/related-organizations/view-peva-municipality.hbs
  app/components/related-organizations/view-peva-province.hbs
  app/components/site-type-select.js
  app/constants/Classification.js
  app/controllers/administrative-units/administrative-unit.js
  app/controllers/administrative-units/administrative-unit/core-data/edit.js
  app/controllers/administrative-units/administrative-unit/core-data/index.js
  app/controllers/administrative-units/administrative-unit/related-organizations/edit.js
  app/controllers/administrative-units/new.js
  app/models/administrative-unit-classification-code.js
  app/models/administrative-unit.js
  app/models/change-event-type.js
  app/routes/administrative-units/administrative-unit/core-data/index.js
  app/templates/administrative-units/administrative-unit.hbs
  app/templates/administrative-units/administrative-unit/core-data/edit.hbs
  app/templates/administrative-units/administrative-unit/core-data/index.hbs
  app/templates/administrative-units/administrative-unit/related-organizations/edit.hbs
  app/templates/administrative-units/administrative-unit/related-organizations/index.hbs
  app/templates/administrative-units/new.hbs
  app/validations/administrative-unit.js
Labels: enhancement

#559 Use identifier instead of structuredIdentifier to detect error
  app/controllers/administrative-units/administrative-unit/core-data/edit.js
  app/controllers/administrative-units/new.js
Labels: bug

#562 Remove personal-information and minister disabled forms
  app/components/contact-details.hbs
  app/components/contact-details.js
  app/components/propagate-contact-details-update.hbs
  app/components/propagate-contact-details-update.js
  app/controllers/administrative-units/administrative-unit/ministers/index.js
  app/controllers/administrative-units/administrative-unit/ministers/new.js
  app/controllers/people/new-position.js
  app/controllers/people/person/personal-information/edit.js
  app/controllers/people/person/personal-information/index.js
  app/controllers/people/person/positions/mandatory/index.js
  app/controllers/people/person/positions/minister/edit.js
  app/controllers/people/person/positions/minister/index.js
  app/models/board-position-code.js
  app/router.js
  app/routes/administrative-units/administrative-unit/ministers/new.js
  app/routes/people/person/personal-information/edit.js
  app/routes/people/person/positions/minister/edit.js
  app/services/contact-details.js
  app/templates/administrative-units/administrative-unit/ministers/index.hbs
  app/templates/administrative-units/administrative-unit/ministers/new.hbs
  app/templates/people/new-position.hbs
  app/templates/people/person/personal-information/edit.hbs
  app/templates/people/person/personal-information/index.hbs
  app/templates/people/person/positions/minister/edit.hbs
  app/templates/people/person/positions/minister/index.hbs
  app/validations/address.js
  app/validations/contact-point.js
  app/validations/minister.js
  app/validations/secondary-contact-point.js
  app/validations/site.js
Labels: internal

#564 Remove people new form
  app/components/person-search-by-name.hbs
  app/components/person-search-by-name.js
  app/components/person-search.hbs
  app/components/person-search.js
  app/components/table-message/has-results.hbs
  app/components/table-message/no-result.hbs
  app/controllers/people/new.js
  app/router.js
  app/routes/people/new.js
  app/styles/_shame.scss
  app/templates/people/new.hbs
  app/validations/person.js
Labels: internal

#565 Migrate `administrative-unit.related-organizations.edit` to the new form validation
  app/components/related-organizations/edit-agb.hbs
  app/components/related-organizations/edit-apb.hbs
  app/components/related-organizations/edit-assistance-zone.hbs
  app/components/related-organizations/edit-central-worship-service.hbs
  app/components/related-organizations/edit-igs.hbs
  app/components/related-organizations/edit-municipality.hbs
  app/components/related-organizations/edit-ocmw-association.hbs
  app/components/related-organizations/edit-ocmw.hbs
  app/components/related-organizations/edit-peva-municipality.hbs
  app/components/related-organizations/edit-peva-province.hbs
  app/components/related-organizations/edit-police-zone.hbs
  app/components/related-organizations/edit-worship-service.hbs
  app/controllers/administrative-units/administrative-unit/related-organizations/edit.js
  app/routes/administrative-units/administrative-unit/related-organizations/edit.js
  app/templates/administrative-units/administrative-unit/related-organizations/edit.hbs
  app/validations/administrative-unit.js
Labels: internal

#555 Feat/integration wegwijs api
  app/controllers/administrative-units/administrative-unit/core-data/index.js
  app/helpers/is-feature-enabled.js
  app/styles/_shame.scss
  app/styles/app.scss
  app/templates/administrative-units/administrative-unit/core-data/index.hbs
  config/environment.js
Labels: enhancement

#563 Replace ander admini... by andere vestiging
  app/components/site-type-select.js
Labels: enhancement

#567 Refactor: migrate change event forms validation to Joi
  app/controllers/administrative-units/administrative-unit/change-events/details/edit.js
  app/controllers/administrative-units/administrative-unit/change-events/details/index.js
  app/controllers/administrative-units/administrative-unit/change-events/new.js
  app/models/change-event-type.js
  app/models/change-event.js
  app/models/decision.js
  app/routes/administrative-units/administrative-unit/change-events/details.js
  app/routes/administrative-units/administrative-unit/change-events/details/edit.js
  app/routes/administrative-units/administrative-unit/change-events/new.js
  app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
  app/templates/administrative-units/administrative-unit/change-events/details/index.hbs
  app/templates/administrative-units/administrative-unit/change-events/new.hbs
  app/utils/datepicker.js
  app/validations/change-event.js
  tests/unit/models/change-event-test.js
  tests/unit/models/decision-test.js
Labels: internal

#569 Fix AGB/APB edit form validation
  app/routes/administrative-units/administrative-unit/core-data.js
Labels: bug

#568 Feat/site names
  app/components/site-type-with-name.hbs
  app/controllers/administrative-units/administrative-unit/sites/new.js
  app/controllers/administrative-units/administrative-unit/sites/site/edit.js
  app/models/site.js
  app/templates/administrative-units/administrative-unit/sites/index.hbs
  app/templates/administrative-units/administrative-unit/sites/new.hbs
  app/templates/administrative-units/administrative-unit/sites/site/edit.hbs
  app/templates/administrative-units/administrative-unit/sites/site/index.hbs
Labels: enhancement
