Repository lblod/frontend-organization-portal, pull requests merged in 2024-03, with the labels that each got.

#584 Fix change-event resulting organization name
  app/routes/administrative-units/administrative-unit/change-events/details.js
  app/templates/administrative-units/administrative-unit/change-events/details/edit.hbs
  app/templates/administrative-units/administrative-unit/change-events/details/index.hbs
Labels: bug

#587 Fix sharepoint and kbo reset in administrative-unit edit form
  app/controllers/administrative-units/administrative-unit/core-data/edit.js
Labels: bug

#588 Fix null value in optional string input
  app/models/address.js
  app/models/change-event.js
  app/models/contact-point.js
  app/models/organization.js
  app/models/site.js
  app/models/worship-service.js
  app/validators/schema.js
Labels: bug

#589 Update ember-data version to 4.12.0
  package-lock.json
  package.json
Labels: bug, internal

#586 Feature: add alternative names for organisations
  app/components/administrative-unit-select-by-name.js
  app/controllers/administrative-units/administrative-unit/core-data/edit.js
  app/helpers/help-text.js
  app/models/organization.js
  app/routes/administrative-units/index.js
  app/templates/administrative-units/administrative-unit/core-data/edit.hbs
  app/templates/administrative-units/administrative-unit/core-data/index.hbs
  app/templates/administrative-units/new.hbs
  app/templates/organizations/organization/core-data.hbs
Labels: enhancement

#591 Fix: correctly set alternative names when creating new administrative units
  app/controllers/administrative-units/new.js
  app/templates/administrative-units/new.hbs
Labels: bug

#593 fix: make relation between Person and AgentInPosition polymorphic
  app/models/agent-in-position.js
  app/models/person.js
Labels: bug

#595 Bump release-it and lerna-changelog plugin
  package-lock.json
  package.json
Labels: internal

#596 Fix: explicitly copy legal and alternative names when creating new units
  app/controllers/administrative-units/new.js
Labels: bug
