Repository lblod/frontend-organization-portal, pull requests merged in 2024-05, with the labels that each got.

#604 refactor: move remaining classification code functionality into model
  app/components/site-type-select.js
  app/constants/Classification.js
  app/controllers/organizations/new.js
  app/controllers/organizations/organization.js
  app/controllers/organizations/organization/core-data/edit.js
  app/controllers/organizations/organization/related-organizations/edit.js
  app/models/administrative-unit-classification-code.js
  app/models/administrative-unit.js
  app/templates/organizations/new.hbs
  app/templates/organizations/organization.hbs
  app/templates/organizations/organization/core-data/edit.hbs
  app/templates/organizations/organization/related-organizations/edit.hbs
Labels: internal

#605 refactor: use "Representative body" instead of "Representative organ"
  app/components/classification-multiple-select.js
  app/constants/Classification.js
  app/controllers/organizations/index.js
  app/models/administrative-unit-classification-code.js
  app/models/administrative-unit.js
  app/models/representative-body.js
  app/utils/classification-identifiers.js
  tests/unit/models/administrative-unit-classification-code-test.js
  tests/unit/models/administrative-unit-test.js
  tests/unit/models/central-worship-service-test.js
  tests/unit/models/organization-test.js
  tests/unit/models/representative-body-test.js
  tests/unit/models/worship-administrative-unit-test.js
  tests/unit/models/worship-service-test.js
Labels: internal

#606 refactor: removed `CLASSIFICATION_CODE` in favour of `CLASSIFICATION`
  app/components/change-event-type-select.js
  app/components/classification-multiple-select.js
  app/components/classification-select.js
  app/components/municipality-select-by-name.js
  app/components/municipality-select.js
  app/components/organization-select.js
  app/components/position-select.js
  app/components/province-organization-select.js
  app/components/province-select.js
  app/components/recognized-worship-type-select.js
  app/components/site-type-select.js
  app/constants/Classification.js
  app/controllers/organizations/index.js
  app/controllers/organizations/organization/local-involvements/edit.js
  app/controllers/people/index.js
  app/models/administrative-unit-classification-code.js
  app/models/administrative-unit.js
  app/routes/organizations/organization/core-data/edit.js
  app/routes/organizations/organization/core-data/index.js
  app/routes/organizations/organization/local-involvements/edit.js
  tests/unit/models/administrative-unit-classification-code-test.js
Labels: internal

#610 Add message when kboOrganization is missing
  app/components/kbo-organization/data-card.hbs
  app/components/kbo-organization/data-card.js
Labels: enhancement

#612 Enable dynamic feature toggles of kbo-data-tab from backend
  config/environment.js
Labels: bug

#611 Generalise organisation creation to operate on the most specific model type
  app/controllers/organizations/new.js
  app/models/administrative-unit.js
  app/models/central-worship-service.js
  app/models/worship-administrative-unit.js
  app/models/worship-service.js
  app/routes/organizations/new.js
  app/templates/organizations/new.hbs
Labels: bug, enhancement

#613 fix: require recognised worship type for central worship services
  app/models/worship-administrative-unit.js
  tests/unit/models/central-worship-service-test.js
  tests/unit/models/worship-service-test.js
Labels: bug

#615 Fix Missing kbo number message
  app/components/kbo-organization/data-card.hbs
  app/templates/administrative-units/administrative-unit/core-data/index.hbs
  app/templates/organizations/organization/core-data.hbs
Labels: bug

#616 Remove `kbo-data-tab` feature flag
  README.md
  app/controllers/administrative-units/administrative-unit/core-data/edit.js
  app/controllers/administrative-units/new.js
  app/templates/administrative-units/administrative-unit/core-data/index.hbs
  app/templates/organizations/organization/core-data.hbs
  config/environment.js
Labels: enhancement

#617 Add missing `representative-body-classification-codes` model
  app/models/representative-body-classification-code.js
Labels: bug

#614 feature: add functionality for private OCMW associations
  app/components/change-event-type-select.js
  app/components/classification-multiple-select.js
  app/components/classification-select.js
  app/constants/Classification.js
  app/controllers/organizations/new.js
  app/controllers/people/index.js
  app/models/administrative-unit-classification-code.js
  app/models/administrative-unit.js
  app/models/registered-organization-classification-code.js
  app/models/registered-organization.js
  app/utils/classification-identifiers.js
  tests/unit/models/administrative-unit-test.js
  tests/unit/models/registered-organization-test.js
Labels: enhancement

#618 fix: correctly update change event decisions after editing
  app/controllers/organizations/organization/change-events/details/edit.js
  app/models/decision.js
Labels: bug

#620 fix: set properties on correct model
  app/templates/organizations/new.hbs
Labels: bug

#619 feature: use KBO organization's name as first fallback
  app/models/organization.js
  tests/unit/models/organization-test.js
Labels: enhancement

#623 fix: correctly include region when editing a PEVA
  app/routes/organizations/organization/core-data/edit.js
  app/templates/organizations/organization/core-data/edit.hbs
Labels: bug
